CREATE TABLE [dbo].[ADwell_known_sids_lookup](
[SID] [nvarchar](128) NOT NULL,
[DisplayName] [nvarchar](128) NULL,
[Description] [nvarchar](512) NULL,
CONSTRAINT [PK_WellKnownSIDsLookup] PRIMARY KEY CLUSTERED 
(
	[SID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
